backend:
  name: git-gateway
  branch: master

media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

# Collections
collections: # A list of collections the CMS should be able to edit
  - name: "Authentication"
    label: "Authentication"
    folder: "content/basic/authentication"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}