backend:
  name: github
  repo: AirGateway/dev-guides
  branch: master

media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

# Collections
collections: # A list of collections the CMS should be able to edit
  - name: "Getting Started"
    label: "Getting Started"
    folder: "content/getting_started"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Authentication"
    label: "Getting Started / Authentication"
    folder: "content/getting_started/authentication"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Sending Requests"
    label: "Getting Started / Sending Requests"
    folder: "content/getting_started/sending_requests_to_our_ndc_api"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Multi-provider requests"
    label: "Getting Started / Multi-provider requests"
    folder: "content/getting_started/multi-provider_requests"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Single provider requests"
    label: "Getting Started / Single Provider Requests"
    folder: "content/getting_started/single-provider_requests"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "NDC JSON APIs Docs"
    label: "NDC JSON APIS DOCS"
    folder: "content/NDC_JSON_API_Docs"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Hub API Docs"
    label: "Hub API Docs"
    folder: "content/Hub_API_Docs"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Consumers"
    label: "Hub API Docs / Consumers"
    folder: "content/Hub_API_Docs/consumers"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Agencies"
    label: "Hub_API_Docs / Agencies"
    folder: "content/Hub_API_Docs/agencies"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Agents"
    label: "Hub_API_Docs / Agents"
    folder: "content/Hub_API_Docs/agents"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Keys"
    label: "Hub_API_Docs / Keys"
    folder: "content/Hub_API_Docs/keys"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Webhooks"
    label: "Webhooks"
    folder: "content/webhooks"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Workflows"
    label: "Workflows"
    folder: "content/workflows"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Booking"
    label: "Workflows / Booking"
    folder: "content/workflows/booking"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Servicing"
    label: "Workflows / Servicing"
    folder: "content/workflows/servicing"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Providers"
    label: "Providers List"
    folder: "content/providers"
    create: false
    slug: "_index"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Weight", name: "weight", widget: "number"}
      - {label: "Menu pre-text", name: "pre", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}